=== r-sadykov/CakeEvent/TestDir/CakeEvent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/CakeEvent" xmlns:tns="http://www.example.org/CakeEvent" elementFormDefault="qualified">
	<element name="CakeEvent">
		<complexType>
			<sequence>
				<element name="name" type="token" minOccurs="1" maxOccurs="1" />
				<element name="autor" type="token" minOccurs="1" maxOccurs="1" />
				<element name="description" type="token" minOccurs="1" maxOccurs="1" />
				<element name="capital" type="double" minOccurs="1" maxOccurs="1" />
				<element ref="tns:ingredients" minOccurs="1" maxOccurs="1" />
				<element ref="tns:recipes" minOccurs="1" maxOccurs="1" />
				<element ref="tns:solution" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
			<attribute name="id" type="token" use="required"/>
			<attribute name="createdAt" type="token" use="optional" />
			<attribute name="solved" type="boolean" use="required" />
			<attribute name="solverStatus" type="token" use="optional" />
		</complexType>
	</element>
	
	<element name="ingredients">
		<complexType>
			<sequence>
				<element ref="tns:ingredient" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	
	<element name="ingredient">
		<complexType>
			<sequence>
				<element name="name" type="token" minOccurs="1" maxOccurs="1" />
				<element name="unit" type="tns:units" minOccurs="1" maxOccurs="1" />
				<element name="price" type="double" minOccurs="1" maxOccurs="1" />
				<element name="stock" type="double" minOccurs="1" maxOccurs="1" />
			</sequence>
			<attribute name="id" type="int" use="required"/>
		</complexType>
	</element>
	
	<element name="recipes">
		<complexType>
			<sequence>
				<element ref="tns:recipe" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	
	<element name="recipe">
		<complexType>
			<sequence>
				<element name="name" type="token" minOccurs="1" maxOccurs="1" />
				<element name="description" type="token" minOccurs="0" maxOccurs="1" />
				<element name="instructions" type="token" minOccurs="1" maxOccurs="1" />
				<element ref="tns:recipe_ingredient" minOccurs="0" maxOccurs="unbounded" />
				<element name="sales_price" type="double" minOccurs="1" maxOccurs="1" />
				<element name="production_lwb" type="double" minOccurs="1" maxOccurs="1" />
				<element name="production_upb" type="double" minOccurs="1" maxOccurs="1" />
			</sequence>
			<attribute name="id" type="int" use="required"/>
		</complexType>
	</element>
	
	<element name="recipe_ingredient">
		<complexType>
			<attribute name="ingredient_id" type="int" use="required"/>
			<attribute name="amount" type="double" use="required"/>
		</complexType>
	</element>
	
	<element name="solution">
		<complexType>
			<sequence>
				<element name="profit" type="double" minOccurs="0" maxOccurs="1" />
				<element name="used_capital" type="double" minOccurs="0" maxOccurs="1" />
				<element ref="tns:production" minOccurs="0" maxOccurs="unbounded" />
				<element ref="tns:used_ingredient" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
			<attribute name="solved" type="boolean" use="required"/>
			<attribute name="solvedAt" type="token" use="optional"/>
			<attribute name="optimal" type="boolean" use="optional"/>
			<attribute name="status" type="token" use="optional"/>
		</complexType>
	</element>
	
	<element name="production">
		<complexType>
			<attribute name="recipe_id" type="int" use="required"/>
			<attribute name="quantity" type="double" use="required"/>
		</complexType>
	</element>
	
	<element name="used_ingredient">
		<complexType>
			<attribute name="ingredient_id" type="int" use="required"/>
			<attribute name="amountStock" type="double" use="required"/>
			<attribute name="amountBuyed" type="double" use="required"/>
			<attribute name="CostBuyed" type="double" use="required"/>
			<attribute name="percentOfCostBuyed" type="double" use="required"/>
		</complexType>
	</element>
	
	<simpleType name="units">
		<restriction base="token">
			<enumeration value="kg" />
			<enumeration value="Liter" />
			<enumeration value="Stck" />
		</restriction>
	</simpleType>
</schema>

=== r-sadykov/CakeEvent/TestDir/1.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<CakeEvent xmlns="http://www.example.org/CakeEvent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="1" createdAt="03.09.2010 15:01:51" solved="true" solverStatus="SOLVER_OK" xsi:noNamespaceSchemaLocation="/Schema/CakeEvent.xsd">
    <name>Kuchen</name>
    <autor>CHristian MÃ¼ller</autor>
    <description>OR Kuchen backen Aufgabe</description>
    <capital>400.0</capital>
    <ingredients>
        <ingredient id="0">
            <name>Mehl</name>
            <unit>kg</unit>
            <price>1.5</price>
            <stock>600.0</stock>
        </ingredient>
        <ingredient id="1">
            <name>Zucker</name>
            <unit>kg</unit>
            <price>2.5</price>
            <stock>250.0</stock>
        </ingredient>
        <ingredient id="2">
            <name>Milch</name>
            <unit>Liter</unit>
            <price>1.2</price>
            <stock>300.0</stock>
        </ingredient>
        <ingredient id="3">
            <name>Eier</name>
            <unit>Stck</unit>
            <price>0.2</price>
            <stock>2400.0</stock>
        </ingredient>
    </ingredients>
    <recipes>
        <recipe id="0">
            <name>Kuchen 1</name>
            <description>Beschreibung des Kuchen 1</description>
            <instructions>Anleitung zum Erstellen eines Kuchen 1</instructions>
            <recipe_ingredient ingredient_id="0" amount="2.0"/>
            <recipe_ingredient ingredient_id="1" amount="0.5"/>
            <recipe_ingredient ingredient_id="2" amount="1.0"/>
            <recipe_ingredient ingredient_id="3" amount="6.0"/>
            <sales_price>6.0</sales_price>
            <production_lwb>0.0</production_lwb>
            <production_upb>INF</production_upb>
        </recipe>
        <recipe id="1">
            <name>Kuchen 2</name>
            <description>Beschreibung des Kuchen 2</description>
            <instructions>Anleitung zum Erstellen eines Kuchen 2</instructions>
            <recipe_ingredient ingredient_id="0" amount="1.0"/>
            <recipe_ingredient ingredient_id="1" amount="1.0"/>
            <recipe_ingredient ingredient_id="2" amount="0.5"/>
            <recipe_ingredient ingredient_id="3" amount="9.0"/>
            <sales_price>8.0</sales_price>
            <production_lwb>0.0</production_lwb>
            <production_upb>INF</production_upb>
        </recipe>
    </recipes>
    <solution solved="true" solvedAt="Sep 25, 2014  7:28:02 PM" optimal="true" status="optimal">
        <profit>3052.03</profit>
        <used_capital>400.0</used_capital>
        <production recipe_id="0" quantity="174.797"/>
        <production recipe_id="1" quantity="250.407"/>
        <used_ingredient ingredient_id="0" amountStock="600.0" amountBuyed="0.0" CostBuyed="0.0" percentOfCostBuyed="0.0"/>
        <used_ingredient ingredient_id="1" amountStock="250.0" amountBuyed="87.8049" CostBuyed="219.51225" percentOfCostBuyed="54.8780625"/>
        <used_ingredient ingredient_id="2" amountStock="300.0" amountBuyed="0.0" CostBuyed="0.0" percentOfCostBuyed="0.0"/>
        <used_ingredient ingredient_id="3" amountStock="2400.0" amountBuyed="902.439" CostBuyed="180.4878" percentOfCostBuyed="45.12195"/>
    </solution>
</CakeEvent>
